#ifndef CRUX_ASSERT_H
#define CRUX_ASSERT_H

#include <stdio.h>
#include <stdlib.h>

#define ASSERT_FATAL(expr, msg)                                                                                                                                                                                                                                                                                                                                        \
	do                                                                                                                                                                                                                                                                                                                                                                 \
	{                                                                                                                                                                                                                                                                                                                                                                  \
		if (!(expr))                                                                                                                                                                                                                                                                                                                                                   \
		{                                                                                                                                                                                                                                                                                                                                                              \
			fprintf(stderr, "ASSERT FATAL FAILED:\n\tExpression: %s\n\tMessage: %s\n\tFile: %s\n\tLine: %d\n", #expr, msg, __FILE__, __LINE__);                                                                                                                                                                                                                        \
			exit(EXIT_FAILURE);                                                                                                                                                                                                                                                                                                                                        \
		}                                                                                                                                                                                                                                                                                                                                                              \
	} while (0)

#define ASSERT_RET(expr, retval)                                                                                                                                                                                                                                                                                                                                       \
	do                                                                                                                                                                                                                                                                                                                                                                 \
	{                                                                                                                                                                                                                                                                                                                                                                  \
		if (!(expr))                                                                                                                                                                                                                                                                                                                                                   \
		{                                                                                                                                                                                                                                                                                                                                                              \
			fprintf(stderr, "ASSERT FAILED:\n\tExpression: %s\n\tFile: %s\n\tLine: %d\n\tReturning: %d\n", #expr, __FILE__, __LINE__, retval);                                                                                                                                                                                                                         \
			return retval;                                                                                                                                                                                                                                                                                                                                             \
		}                                                                                                                                                                                                                                                                                                                                                              \
	} while (0)

#endif // CRUX_ASSERT_H